In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import statsmodels.api as sm

In [2]:
dataset = pd.read_csv("ovb.csv")

In [3]:
dataset

,state,age,wagesal,imm,hispanic,black,asian,educ,wage,logwage,female,fedwkr,statewkr,localwkr
0,11,44,18000,0,0,0,0,14,9.109312,2.209297,1,1,0,0
1,11,39,18000,0,0,0,0,14,18.000000,2.890372,0,0,0,0
2,11,39,35600,0,0,0,0,12,17.115385,2.839978,0,0,0,1
3,11,39,8000,0,0,0,0,14,5.128205,1.634756,1,0,0,0
4,11,39,100000,0,0,0,0,16,38.461538,3.649659,0,1,0,0
5,11,43,25000,0,0,0,0,12,10.000000,2.302585,0,0,0,0
6,11,38,25000,0,0,0,0,16,27.173913,3.302257,1,0,0,0
7,11,39,26000,0,0,0,0,13,16.666667,2.813411,1,0,0,0
8,11,39,52000,0,0,0,0,16,16.666667,2.813411,0,0,0,0
9,11,37,4500,0,0,0,0,13,4.000000,1.386294,1,0,0,0
10,11,42,26000,0,0,0,0,14,16.666667,2.813411,1,0,0,0
11,11,37,34000,0,0,0,0,12,16.346154,2.793993,0,0,1,0
12,11,42,65000,0,0,0,0,13,31.250000,3.442019,1,0,0,0
13,11,41,14300,0,0,0,0,12,17.875000,2.883403,1,0,0,0
14,11,35,15000,0,0,0,0,14,7.796258,2.053644,0,0,0,0
15,11,39,65000,0,0,0,0,16,25.000000,3.218876,1,0,0,0
16,11,38,40000,0,0,0,0,14,19.230769,2.956512,1,1,0,0
17,11,37,53000,0,0,0,0,13,22.649573,3.120141,0,0,0,0
18,11,35,1098,0,0,0,0,13,5.490000,1.702928,1,0,0,0
19,11,44,36000,0,0,0,0,16,12.587413,2.532697,1,0,1,0
20,11,40,40000,0,0,0,0,16,19.230769,2.956512,1,0,0,0
21,11,44,40000,0,0,0,0,12,19.230769,2.956512,0,0,1,0
22,11,35,33500,0,0,0,0,13,16.105769,2.779178,1,0,0,0
23,11,39,34000,0,0,0,0,12,16.346154,2.793993,0,0,0,0
24,11,35,22000,0,0,0,0,16,11.133603,2.409968,0,0,0,0
25,11,39,18000,0,0,0,0,13,10.817308,2.381147,1,0,0,0
26,11,40,4500,0,0,0,0,12,4.000000,1.386294,0,0,0,0
27,11,44,18200,0,0,0,0,13,8.750000,2.169054,1,0,0,0
28,11,36,33000,0,0,0,0,16,15.865385,2.764140,1,0,0,1
29,11,37,12000,0,0,0,0,14,9.615385,2.263364,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21877,95,37,39000,0,0,0,0,13,18.750000,2.931194,0,0,0,0
21878,95,42,35000,1,0,0,1,14,16.826923,2.822980,0,0,0,0
21879,95,40,15000,1,1,0,0,12,8.241758,2.109214,1,0,0,0
21880,95,37,40000,1,1,0,0,12,19.230769,2.956512,0,0,0,0
21881,95,40,52000,0,0,0,0,14,25.000000,3.218876,1,0,0,0
21882,95,37,75000,0,0,0,1,13,72.115385,4.278267,0,0,0,1
21883,95,37,3000,1,0,0,1,13,4.000000,1.386294,0,0,0,0
21884,95,40,3000,1,0,0,1,13,4.000000,1.386294,1,0,0,0
21885,95,36,40000,0,0,0,1,16,20.000000,2.995732,1,0,0,0
21886,95,44,144000,0,0,0,0,16,46.153846,3.831980,1,0,0,0
21887,95,41,42002,0,1,0,0,13,20.193269,3.005349,0,1,0,0
21888,95,35,52500,0,0,0,0,13,32.812500,3.490810,1,1,0,0
21889,95,36,30000,0,0,0,0,16,36.057692,3.585120,1,0,0,0
21890,95,44,130000,0,0,0,1,16,62.500000,4.135167,0,1,0,0
21891,95,36,92000,0,0,0,0,16,44.230769,3.789421,0,1,0,0
21892,95,36,42000,0,0,0,0,12,20.192308,3.005302,1,1,0,0
21893,95,43,12000,1,0,0,0,12,7.692308,2.040221,1,0,0,0
21894,95,36,35000,0,0,0,1,12,19.230769,2.956512,0,0,0,0
21895,95,42,1820,0,0,0,0,12,7.000000,1.945910,0,0,0,0
21896,95,42,80000,0,0,0,0,16,38.461538,3.649659,0,0,0,0
21897,95,42,65000,0,0,0,0,18,31.250000,3.442019,1,1,0,0
21898,95,40,50000,0,1,0,0,12,24.038462,3.179655,0,0,0,0
21899,95,35,31000,0,0,0,0,12,14.903846,2.701619,0,0,1,0
21900,95,35,30000,0,0,0,0,12,12.396694,2.517430,1,0,0,0
21901,95,37,15600,1,0,0,1,12,7.500000,2.014903,0,0,0,0
21902,95,36,125000,0,0,0,0,18,60.096154,4.095946,0,0,1,0
21903,95,38,70000,0,0,0,1,18,26.923077,3.292984,1,0,0,0
21904,95,43,48208,0,0,0,0,14,20.601709,3.025374,1,0,0,0
21905,95,43,75000,0,0,0,0,18,36.057692,3.585120,0,0,0,0
21906,95,44,50000,1,0,0,1,20,24.038462,3.179655,1,0,1,0

Question 2(a): 

Using the omitted variable formula, write out an expression for the OLS estimate of the coefficient on immigrant status from model (1) if the true model is (5). 

True Model: $\log(wage)$ = $\epsilon_{i}$ + $\beta_{1} Educ_{i}$ + $\beta_{2} Imm_{i}$ 

$\epsilon_{i}$ is the constant term, $Educ_{i}$ is the education variable, and $Imm_{i}$ is the immigration variable. 

Model (1): $\log(wage)$ = $\epsilon_{i}$ + $\beta_{1} Imm_{i}$

$\epsilon_{i}$ is the constant term and $Imm_{i}$ is the immigration variable. 

An auxiliary regression we can run to OLS estimate the true coefficient of immigrant status would be: 

$Educ_{i}$ = $\epsilon_{i}$ + $\pi_{1} Imm_{i}$

where $Educ_{i}$ is the missing education variable, $\epsilon_{i}$ is the error term, $Imm_{i}$ is the immigration variable, and $\pi_{1}$ is the effect of immigration on education. 

We can then use Frisch-Waugh Theorem with the true model as follows: 

$\log(wage)$ = $\epsilon_{i}$ + $\beta_{1} Educ_{i}$ + $\beta_{2} Imm_{i}$ 

$\log(wage)$ = $\epsilon_{i}$ + $\beta_{1} (\epsilon_{i} + \pi_{1} Imm_{i})$ + $\beta_{2} Imm_{i}$

$\log(wage)$ = $\epsilon_{i}$ + $\beta_{1}\epsilon_{i} + \beta_{1}\pi_{1} Imm_{i} + \beta_{2} Imm_{i}$ 

$\log(wage)$ = (1 + $\beta_{1}) \epsilon_{i} + (\beta_{1}\pi_{1} + \beta_{2}) Imm_{i}$ 

Thus, the OLS estimate of the coefficient on immigrant status from model (1) if the true model is (5) is ($\beta_{1} \pi_{1} + \beta_{2}$).

Question 2(b):

Using a regression package, estimate the 5 models, and show the values
of the terms for part (a), First for females, then for males. Your answers for
females should be the same as the ones reported in the table in Lecture 5.

In [10]:
immigrant_female = dataset.loc[dataset['female'] == 1, ['logwage', 'imm']]
immigrant_male = dataset.loc[dataset['female'] == 0, ['logwage', 'imm']]
#this will store all of the immigrant data in a dataframe, split by male and female.

In [16]:
immigrant_male = sm.add_constant(immigrant_male)
#adding a constant to our data to run for model 1.

In [23]:
model1 = sm.OLS(immigrant_male['logwage'], immigrant_male['imm'], hasconst = True)
results1 = model1.fit()

In [24]:
print(results1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                logwage   R-squared:                     -16.249
Model:                            OLS   Adj. R-squared:                -16.249
Method:                 Least Squares   F-statistic:                      -inf
Date:                Thu, 14 Feb 2019   Prob (F-statistic):                nan
Time:                        14:22:56   Log-Likelihood:                -27975.
No. Observations:               11306   AIC:                         5.595e+04
Df Residuals:                   11305   BIC:                         5.596e+04
Df Model:                           0
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
imm            2.9111      0.058     50.324      0.000       2.798       3.025
==============================================================================
Omnibus:                     1272.137   Durbin-Watson:                   0.422
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1759.593
Skew:                          -0.966   Prob(JB):                         0.00
Kurtosis:                       3.017   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.